### ISSUE TITLE
Excluding the first part of a chapter reference in a category confuses random

### ISSUE THREAD

**Issue by zostay** [zostay/today#43]
Because of #42 I can't just use a short `--exclude` to demonstrate this, but given this index file:

```yaml
# index.yaml
metadata:
    version: 0
    original_version: 0
description: 'Index of verses for '
verses:
    2024/01/01:
        reference: Daniel 6:1-7:19
```

And then running:

```shell
today random -M1 --exclude-index index.yaml -c Apocalyptic
```

The `today` program will panic with this error:

```
panic: scripture reference not found

goroutine 1 [running]:
github.com/zostay/today/cmd.RunTodayRandom(0x105494680, {0x1400126abe0?, 0x4?, 0x104e557fc?})
        /Users/sterling/projects/go/src/github.com/zostay/today/cmd/random.go:119 +0x914
github.com/spf13/cobra.(*Command).execute(0x105494680, {0x1400126ab90, 0x5, 0x5})
        /Users/sterling/projects/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x140008cc908)
        /Users/sterling/projects/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/sterling/projects/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/zostay/today/cmd.Execute()
        /Users/sterling/projects/go/src/github.com/zostay/today/cmd/root.go:33 +0x24
main.main()
        /Users/sterling/projects/go/src/github.com/zostay/today/main.go:6 +0x1c
```

I don't understand yet why the Daniel 6 inclusion matters here since the Apocalyptic category only contains Daniel 7-8, but if I try to just exclude Daniel 7:1-19, then this panic does not occur.

**Comment by zostay** [comment]
After some digging, the issue is that the `Subtract` method that calculates the set difference between two verse references incorrectly handled subtracting from the beginning or end of the verse. So this operation worked correctly:

```
Daniel 7:1-12:13 (-) Daniel 7:1-19
```

Would correctly rewrite the subtracted reference as:

```
Daniel 7:20-12:13
```

However, this operation failed:

```
Daniel 7:1-12:13 (-) Daniel 6:1-7:19
```

As it incorrectly assumed that removal of the front would always match the first verse exactly, so the result was unchanged:

```
Daniel 7-12
```
